#!/bin/sh
set -e
# Automatically added by dh_installinit/12.10ubuntu1
if [ "$1" = "purge" ] ; then
	update-rc.d grub-common remove >/dev/null
fi
# End automatically added section
# Automatically added by dh_installdeb/12.10ubuntu1
dpkg-maintscript-helper rm_conffile /etc/bash_completion.d/grub 2.02\+dfsg1-9\~ -- "$@"
dpkg-maintscript-helper rm_conffile /etc/grub.d/10_freebsd 2.00-14\~ -- "$@"
dpkg-maintscript-helper rm_conffile /etc/grub.d/10_hurd 2.00-14\~ -- "$@"
# End automatically added section
# Automatically added by dh_systemd_start/12.10ubuntu1
if [ -d /run/systemd/system ]; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_systemd_enable/12.10ubuntu1
if [ "$1" = "remove" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper mask 'grub-initrd-fallback.service' >/dev/null || true
	fi
fi

if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'grub-initrd-fallback.service' >/dev/null || true
		deb-systemd-helper unmask 'grub-initrd-fallback.service' >/dev/null || true
	fi
fi
# End automatically added section
# Automatically added by dh_installdebconf/12.10ubuntu1
if [ "$1" = purge ] && [ -e /usr/share/debconf/confmodule ]; then
	. /usr/share/debconf/confmodule
	db_purge
fi
# End automatically added section
