#!/bin/sh
set -e
# Automatically added by dh_installinit/12.10ubuntu1
if [ -x "/etc/init.d/grub-common" ] && [ "$1" = remove ]; then
	invoke-rc.d grub-common stop || exit 1
fi
# End automatically added section
# Automatically added by dh_installdeb/12.10ubuntu1
dpkg-maintscript-helper rm_conffile /etc/bash_completion.d/grub 2.02\+dfsg1-9\~ -- "$@"
dpkg-maintscript-helper rm_conffile /etc/grub.d/10_freebsd 2.00-14\~ -- "$@"
dpkg-maintscript-helper rm_conffile /etc/grub.d/10_hurd 2.00-14\~ -- "$@"
# End automatically added section
# Automatically added by dh_systemd_start/12.10ubuntu1
if [ -d /run/systemd/system ] && [ "$1" = remove ]; then
	deb-systemd-invoke stop 'grub-initrd-fallback.service' >/dev/null || true
fi
# End automatically added section
